name: quiz_clean_archi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: ^6.2.1 
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.3
  uuid: ^4.4.2
  scrollable_text: ^0.0.3
  pushable_button: ^0.0.4
  url_launcher: ^6.3.0
  # marquee: ^2.2.3
  # text_scroll: ^0.2.0
  audioplayers: ^6.0.0
  # liquid_progress_indicator_v2: ^0.5.0
  html: ^0.15.4
  share_plus: ^9.0.0
  flutter_spinkit: ^5.2.1
  firebase_messaging: ^15.0.3
  http: ^1.2.2
  firebase_core: any
  cloud_firestore: ^5.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/sounds/
  uses-material-design: true

