name: quiz_clean_archi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: ^6.2.1 
  flutter_spinkit: ^5.2.1
  firebase_messaging: ^15.0.3
  firebase_core: any
  cloud_firestore: ^5.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
    - assets/sounds/
  uses-material-design: true

