import 'package:flutter/material.dart';
import 'package:quiz_clean_archi/domain/const/global_const.dart';
import 'package:quiz_clean_archi/infrastructure/theme/color_scheme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/app_bar_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/drawer_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/icon_button_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/icon_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/page_transition_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/popup_menu_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/primary_icon_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/snackbar_theme.dart';
import 'package:quiz_clean_archi/infrastructure/theme/widgetsTheme/text_theme.dart';

class AppTheme {
  AppTheme._();

  factory AppTheme() {
    return instance;
  }

  static final AppTheme instance = AppTheme._();

  ThemeData get light {
    return ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorScheme: colorSchemelight,
        fontFamily: appFontFamily,
        appBarTheme: appbarthemelight,
        iconTheme: iconThemeData,
        // textTheme: txtTheme,
        // primaryTextTheme: txtTheme,
        // bottomNavigationBarTheme: bottomNavigationBarTheme,
        // bannerTheme: bannerTheme,
        // bottomAppBarTheme: bottomAppBarTheme,
        // bottomSheetTheme: bottomSheetTheme,
        // buttonBarTheme: buttonBarTheme,
        // buttonTheme: buttonTheme,
        shadowColor: colorSchemelDark.shadow,
        canvasColor: colorSchemelight.surface,
        // cardTheme: cardTheme,
        // checkboxTheme: checkboxTheme,
        // chipTheme: chipThemeData,
        // dataTableTheme: dataTableTheme,
        // datePickerTheme: datePickerTheme,
        // dialogTheme: dialogTheme,
        // dividerTheme: dividerTheme,
        drawerTheme: drawerTheme,
        // elevatedButtonTheme: elevatedButtonTheme,
        // expansionTileTheme: expansionTileTheme,
        // inputDecorationTheme: inputDecorationTheme,
        // filledButtonTheme: filledButtonTheme,
        iconButtonTheme: iconButtonTheme,
        // outlinedButtonTheme: outlinedButtonTheme,
        // radioTheme: radioThemeData,
        // textButtonTheme: textButtonTheme,
        // switchTheme: switchTheme,
        // toggleButtonsTheme: toggleButtonsTheme,
        // tooltipTheme: tooltipTheme,
        // timePickerTheme: timePickerTheme,
        // tabBarTheme: tabBarTheme,
        snackBarTheme: snackBarTheme,
        // segmentedButtonTheme: segmentedButtonTheme,
        // listTileTheme: listTileTheme,
        // menuButtonTheme: menuButtonTheme,
        // sliderTheme: sliderTheme,
        // menuTheme: menuTheme,
        // menuBarTheme: menuBarTheme,
        // floatingActionButtonTheme: floatingActionButtonTheme,
        // navigationBarTheme: navigationBarTheme,
        // navigationRailTheme: navigationRailTheme,
        pageTransitionsTheme: pageTransitionsTheme,
        popupMenuTheme: popupMenuTheme,
        // scrollbarTheme: scrollbarTheme,
        // searchBarTheme: searchBarTheme,
        // searchViewTheme: searchViewTheme,
        // progressIndicatorTheme: progressIndicatorTheme,
        splashFactory: InkRipple.splashFactory,
        // textSelectionTheme: textSelectionTheme,
        // navigationDrawerTheme: navigationDrawerTheme,
        focusColor: colorSchemelight.primary,
        // typography: typography,
        // dropdownMenuTheme: dropdownMenuTheme,
        // primarySwatch: primaryMaterial,
        cardColor: colorSchemelight.surface,
        dialogBackgroundColor: colorSchemelight.surface,
        disabledColor: colorSchemelight.onSurface.withOpacity(0.38),
        dividerColor: colorSchemelight.outline,
        highlightColor: colorSchemelight.primaryContainer,
        hintColor: colorSchemelight.onSurfaceVariant,
        hoverColor: colorSchemelight.secondaryContainer.withOpacity(0.08),
        primaryColor: colorSchemelight.primary,
        primaryColorDark: colorSchemelight.primaryContainer,
        primaryColorLight: colorSchemelight.primaryContainer,
        secondaryHeaderColor: colorSchemelight.secondaryContainer,
        splashColor: colorSchemelight.secondaryContainer.withOpacity(0.12),
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        primaryIconTheme: primaryIconTheme,
        indicatorColor: colorSchemelight.secondary,
        unselectedWidgetColor: colorSchemelight.onSurface.withOpacity(0.60),
        visualDensity: VisualDensity.adaptivePlatformDensity,
        applyElevationOverlayColor: false,
        scaffoldBackgroundColor: colorSchemelight.surface);
  }

  ThemeData get dark {
    return ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: colorSchemelDark,
        fontFamily: appFontFamily,
        appBarTheme: appbarthemedark,
        iconTheme: darkIconThemeData,
        // textTheme: darkTxtTheme,
        primaryTextTheme: darkTxtTheme,
        // bottomNavigationBarTheme: darkBottomNavigationBarTheme,
        // bannerTheme: darkBannerTheme,
        // bottomAppBarTheme: darkBottomAppBarTheme,
        // bottomSheetTheme: darkBottomSheetTheme,
        // buttonBarTheme: darkButtonBarTheme,
        // buttonTheme: darkButtonTheme,
        shadowColor: colorSchemelDark.shadow,
        canvasColor: colorSchemelDark.surface,
        // cardTheme: darkCardTheme,
        // checkboxTheme: darkCheckboxTheme,
        // chipTheme: darkChipThemeData,
        // dataTableTheme: darkDataTableTheme,
        // datePickerTheme: darkDatePickerTheme,
        // dialogTheme: darkDialogTheme,
        // dividerTheme: darkDividerTheme,
        drawerTheme: darkDrawerTheme,
        // elevatedButtonTheme: darkElevatedButtonTheme,
        // expansionTileTheme: darkExpansionTileTheme,
        // inputDecorationTheme: darkInputDecorationTheme,
        // filledButtonTheme: darkFilledButtonTheme,
        iconButtonTheme: darkIconButtonTheme,
        // outlinedButtonTheme: darkOutlinedButtonTheme,
        // radioTheme: darkRadioThemeData,
        // textButtonTheme: darkTextButtonTheme,
        // switchTheme: darkSwitchTheme,
        // toggleButtonsTheme: darkToggleButtonsTheme,
        // tooltipTheme: darkTooltipTheme,
        // timePickerTheme: darkTimePickerTheme,
        // tabBarTheme: darkTabBarTheme,
        snackBarTheme: darkSnackBarTheme,
        // segmentedButtonTheme: darkSegmentedButtonTheme,
        // listTileTheme: darkListTileTheme,
        // menuButtonTheme: darkMenuButtonTheme,
        // sliderTheme: darkSliderTheme,
        // menuTheme: darkMenuTheme,
        // menuBarTheme: darkMenuBarTheme,
        // floatingActionButtonTheme: darkFloatingActionButtonTheme,
        // navigationBarTheme: darkNavigationBarTheme,
        // navigationRailTheme: darkNavigationRailTheme,
        pageTransitionsTheme: darkPageTransitionsTheme,
        popupMenuTheme: darkPopupMenuTheme,
        // scrollbarTheme: darkScrollbarTheme,
        // searchBarTheme: darkSearchBarTheme,
        // searchViewTheme: darkSearchViewTheme,
        // progressIndicatorTheme: darkProgressIndicatorTheme,
        splashFactory: InkRipple.splashFactory,
        // textSelectionTheme: darkTextSelectionTheme,
        // navigationDrawerTheme: darkNavigationDrawerTheme,
        focusColor: colorSchemelDark.primary,
        // typography: darkTypography,
        // dropdownMenuTheme: darkDropdownMenuTheme,
        // primarySwatch: darkPrimaryMaterial,
        cardColor: colorSchemelDark.surface,
        dialogBackgroundColor: colorSchemelDark.surface,
        disabledColor: colorSchemelDark.onSurface.withOpacity(0.38),
        dividerColor: colorSchemelDark.outline,
        highlightColor: colorSchemelDark.primaryContainer,
        hintColor: colorSchemelDark.onSurfaceVariant,
        hoverColor: colorSchemelDark.secondaryContainer.withOpacity(0.08),
        primaryColor: colorSchemelDark.primary,
        primaryColorDark: colorSchemelDark.primaryContainer,
        primaryColorLight: colorSchemelDark.primaryContainer,
        secondaryHeaderColor: colorSchemelDark.secondaryContainer,
        splashColor: colorSchemelDark.secondaryContainer.withOpacity(0.12),
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        primaryIconTheme: darkPrimaryIconTheme,
        indicatorColor: colorSchemelDark.secondary,
        unselectedWidgetColor: colorSchemelDark.onSurface.withOpacity(0.60),
        visualDensity: VisualDensity.adaptivePlatformDensity,
        applyElevationOverlayColor: false,
        scaffoldBackgroundColor: colorSchemelDark.surface);
  }
}
